// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FloatinButton: typeof import('./components/FloatinButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar.vue')['default']
    TheTopbar: typeof import('./components/TheTopbar.vue')['default']
  }
}
