// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./components/TheSidebar copy.vue')['default']
    FloatinButton: typeof import('./components/FloatinButton.vue')['default']
    FloatingAction: typeof import('./components/landing/FloatingAction.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheCTA: typeof import('./components/landing/TheCTA.vue')['default']
    TheFeatures: typeof import('./components/landing/TheFeatures.vue')['default']
    TheFooter: typeof import('./components/landing/TheFooter.vue')['default']
    TheHeader: typeof import('./components/landing/TheHeader.vue')['default']
    TheHero: typeof import('./components/landing/TheHero.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar.vue')['default']
    TheTopbar: typeof import('./components/TheTopbar.vue')['default']
  }
}
